# These are supported funding model platforms

github: DPBandA
patreon: # Replace with a single Patreon username
open_collective: jmts
ko_fi: dpbennett
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: JMTS
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: "https://www.paypal.com/paypalme/dpbaltd"
