create table `accpac`.AROBL
(
	IDINVC CHAR(22) not null primary key,
        IDCUST CHAR(12),
	AMTDUETC DECIMAL(10,3),
	AMTDUEHC DECIMAL(10,3),
	FISCYR CHAR(4),
	DATEINVC DECIMAL(9,0),
        DATEDUE DECIMAL(9,0),
        AMTINVCHC DECIMAL(10,3),
        AMTINVCTC DECIMAL(10,3),
        DATEPAID DECIMAL(9,0),
        TRXTYPEID SMALLINT(5),
        TRXTYPETXT SMALLINT(5),
        SWPAID SMALLINT(5)
)